import styles from "./style.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create generic Next App",
  description: "Generated by create next app",
};

export default function Contact(params: any) {
  return (
    <>
      <div className={styles.wrap}>
        <h1>Contact</h1>
      </div>
    </>
  );
}
