"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create generic Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebar, setSidebar] = useState<boolean>(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar sidebar={sidebar} />
        <Sidebar sidebar={sidebar} setSidebar={setSidebar} />

        <div
          onClick={() => setSidebar(false)}
          onWheel={() => setSidebar(false)}
          className="content"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
